// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Models;

namespace AirLIine_MVC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220105070029_airLine1")]
    partial class airLine1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AirLIine_MVC.Models.TblPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Mabda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAirline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maghsad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("saat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tarikh")
                        .HasColumnType("datetime2");

                    b.Property<int>("zarfiat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblPlans");
                });

            modelBuilder.Entity("AirLIine_MVC.Models.TblReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblReservations");
                });

            modelBuilder.Entity("AirLIine_MVC.Models.TblUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CodeMeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
